/** Sahifa segmenti uchun layout.js eksportlari */
import { createSeoLayout } from './create-segment-layout'

export const metroXaritasiSeo = createSeoLayout('metro-xaritasi')
export const metroRejasiSeo = createSeoLayout('metro-rejasi')
export const tolovUsullariSeo = createSeoLayout('tolov-usullari')
export const attoKartalarSeo = createSeoLayout('atto-kartalar')
export const attoIlovaSeo = createSeoLayout('atto-ilova')
export const facepaySeo = createSeoLayout('facepay')
export const palmpaySeo = createSeoLayout('palmpay')
export const foydalanishQoidalariSeo = createSeoLayout('foydalanish-qoidalari')
export const davlatRamzlariSeo = createSeoLayout('davlat-ramzlari')
export const murojaatlarSeo = createSeoLayout('murojaatlar')
export const statistikaSeo = createSeoLayout('statistika')
export const yangiliklarSeo = createSeoLayout('yangiliklar')
export const korrupsiyaSeo = createSeoLayout('korrupsiya')
export const tenderlarSeo = createSeoLayout('tenderlar')
export const mediatekaSeo = createSeoLayout('mediateka')
export const metropolitenTarixiSeo = createSeoLayout('metropoliten-tarixi')
export const rahbariyatSeo = createSeoLayout('rahbariyat')
export const tashkiliyTuzilmaSeo = createSeoLayout('tashkiliy-tuzilma')
export const vakansiyalarSeo = createSeoLayout('vakansiyalar')
export const haqimizdaSeo = createSeoLayout('haqimizda')
export const genderTenglikSeo = createSeoLayout('gender-tenglik')
export const normativHujjatlarSeo = createSeoLayout('normativ-hujjatlar')
export const biznesRivojlanishSeo = createSeoLayout('biznes-rivojlanish')
export const buxgalteriyaBalansiSeo = createSeoLayout('buxgalteriya-balansi')
export const aiYordamchiSeo = createSeoLayout('ai-yordamchi')
export const aloqaSeo = createSeoLayout('aloqa')
export const kirishSeo = createSeoLayout('kirish')
export const royxatdanOishSeo = createSeoLayout('royxatdan-otish')
